#!/bin/bash

#Script para quebra de hash

if [ "$1" == "" ] #testa o argumento
then
	echo " "
	echo "Siga o exemplo abaixo para passagem de parametros, passando a wordlist, tipo de encriptacao e o hash"
	echo " "
	echo " $0 /usr/share/wordlists/rockyou.txt md5 698dc19d489c4e4db73e28a713eab07b"
	echo " "

else

    if [ "$2" == "sha256" ]
    then
   	 for i in $(cat $1)
   	 do
   		 clear
   		 cypher=$(echo -n $i | sha256sum | cut -d " " -f1)
   		 echo "Testando $cypher"
   		 if [ $3 == $cypher ]
   		 then
   			echo "[+][+] decrypt -- $i [+][+]"
   			echo " "
   			echo "¯\_(ツ)_/¯"
    			echo " "
   			break
   		 fi
   	 done
    fi

    if [ "$2" == "sha1" ]
    then
   	 for i in $(cat $1)
   	 do
   		 clear
   		 cypher=$(echo -n $i | sha1sum | cut -d " " -f1)
   		 echo "Testando $cypher"
   		 if [ $3 == $cypher ]
   		 then
   			echo "[+][+] decrypt -- $i [+][+]"
			echo " "
   			echo "¯\_(ツ)_/¯"
    			echo " "
   			break
   		 fi
   	 done
    fi
    
        if [ "$2" == "sha512" ]
    then
   	 for i in $(cat $1)
   	 do
   		 clear
   		 cypher=$(echo -n $i | sha512sum | cut -d " " -f1)
   		 echo "Testando $cypher"
   		 if [ $3 == $cypher ]
   		 then
   			echo "[+][+] decrypt -- $i [+][+]"
			echo " "
   			echo "¯\_(ツ)_/¯"
    			echo " "
   			break
   		 fi
   	 done
    fi

    if [ "$2" == "md5" ]
    then
   	 for i in $(cat $1)
   	 do
   		 clear
   		 cypher=$(echo -n $i | md5sum | cut -d " " -f1)
   		 echo "Testando $cypher"
   		 if [ $3 == $cypher ]
   		 then
   			echo "[+][+] decrypt -- $i [+][+]"
			echo " "
   			echo "¯\_(ツ)_/¯"
    			echo " "
   			break
   		 fi
   	 done
    fi
fi
