#!/bin/bash

arquivos=$(ls /root/criptografia/teste)

openssl genrsa -out privada.pem 2048

openssl rsa -in privada.pem -outform PEM -pubout -out publica.pem

for a in $arquivos
do
        if [ "$a" != "script_crypto.sh" ] && [ "$a" != "privada.pem" ] && [ "$a" != "publica.pem" ]; then
        openssl rsautl -in "$a" -out "$a.rsa" -encrypt -pubin -inkey publica.pem
        #rm -rf $a
        fi
done
